// Practice12/practice12/angular-calculator/src/app/calculator/calculator.component.ts
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { display, clear, calculate } from '../store/actions/calculator.actions';
import { State } from '../store'; // import the State interface

@Component({
  selector: 'app-calculator',
  templateUrl: './calculator.component.html',
  styleUrls: ['./calculator.component.css']
})
export class CalculatorComponent {
  result$ = this.store.select(state => state.calculator);

  constructor(private store: Store<State>) { } // provide the State interface as a type parameter

  display(number: string): void {
    this.store.dispatch(display({ number }));
  }

  clear(): void {
    this.store.dispatch(clear());
  }

  calculate(): void {
    this.store.dispatch(calculate());
  }
}

<div class="calculator">
    <div>
        <input class="display-box" type="text" [value]="result$ | async" disabled />
        <input type="button" value="C" (click)="clear()" id="btn" />
      </div>
    <div>
      <input type="button" value="1" (click)="display('1')" />
      <input type="button" value="2" (click)="display('2')" />
      <input type="button" value="3" (click)="display('3')" />
      <input type="button" value="/" (click)="display('/')" />
    </div>
    <div>
      <input type="button" value="4" (click)="display('4')" />
      <input type="button" value="5" (click)="display('5')" />
      <input type="button" value="6" (click)="display('6')" />
      <input type="button" value="-" (click)="display('-')" />
    </div>
    <div>
      <input type="button" value="7" (click)="display('7')" />
      <input type="button" value="8" (click)="display('8')" />
      <input type="button" value="9" (click)="display('9')" />
      <input type="button" value="+" (click)="display('+')" />
    </div>
    <div>
      <input type="button" value="." (click)="display('.')" />
      <input type="button" value="0" (click)="display('0')" />
      <input type="button" value="=" (click)="calculate()" id="btn" />
      <input type="button" value="*" (click)="display('*')" />
    </div>
  </div>

// Practice12/practice12/calculator-react/src/features/calculator/Calculator.jsx
import React from "react";
import "../../styles.css";
import { useDispatch, useSelector } from "react-redux";
import { addInput, resetInput, calculateResult } from "./calculatorSlice";

export default function Calculator() {
  const dispatch = useDispatch();
  const expression = useSelector((state) => state.calculator);

  const buttonOnClick = (e) => {
    dispatch(addInput(e.target.value));
  };

  const reset = () => {
    dispatch(resetInput());
  };

  const calculate = () => {
    dispatch(calculateResult());
  };

  return (
    <>
      <table className="calculator">
        <tbody>
          <tr>
            <td colSpan={3}>
              <input
                className="display-box"
                defaultValue={expression}
                type="text"
                id="result"
                disabled=""
              />
            </td>
            {/* clearScreen() function clears all the values */}
            <td>
              <input type="button" defaultValue="C" onClick={reset} id="btn" />
            </td>
          </tr>
          <tr>
            {/* display() function displays the value of clicked button */}
            <td>
              <input type="button" defaultValue={1} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue={2} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue={3} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue="/" onClick={buttonOnClick} />
            </td>
          </tr>
          <tr>
            <td>
              <input type="button" defaultValue={4} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue={5} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue={6} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue="-" onClick={buttonOnClick} />
            </td>
          </tr>
          <tr>
            <td>
              <input type="button" defaultValue={7} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue={8} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue={9} onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue="+" onClick={buttonOnClick} />
            </td>
          </tr>
          <tr>
            <td>
              <input type="button" defaultValue="." onClick={buttonOnClick} />
            </td>
            <td>
              <input type="button" defaultValue={0} onClick={buttonOnClick} />
            </td>
            <td>
              <input
                type="button"
                defaultValue="="
                onClick={calculate}
                id="btn"
              />
            </td>
            <td>
              <input type="button" defaultValue="*" onClick={buttonOnClick} />
            </td>
          </tr>
        </tbody>
      </table>
    </>
  );
}
